# Generated by Django 3.1 on 2021-01-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='breed',
            new_name='varietal',
        ),
        migrations.AddField(
            model_name='plant',
            name='light_requirement',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
