# Generated by Django 3.1 on 2021-01-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watering',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='plant',
            name='water_requirement',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(verbose_name='date watered'),
        ),
    ]
