# Generated by Django 3.1 on 2021-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210105_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(choices=[('1', '4-4-4'), ('2', '4-8-12'), ('N', 'None')], default='1', max_length=1)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizers',
            field=models.ManyToManyField(to='main_app.Fertilizer'),
        ),
    ]
